### ISSUE TITLE
idlharness.js throws assert error when testing attribute of promise type

### ISSUE THREAD

**Issue by zhaobin2016** [w3c/testharness.js#228]
Given idl like this:

interface PresentationReceiver {
    [SameObject]
    readonly attribute Promise<PresentationConnectionList> connectionList;
};

Get following error:
assert_own_property: Attribute with a Promise type has a then property expected property "then" missing
    at self.IdlArray.IdlArray.assert_type_is (http://web-platform.test:8000/resources/idlharness.js:451:9)
    at IdlInterface.&lt;anonymous&gt; (http://web-platform.test:8000/resources/idlharness.js:1582:40)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1406:25)
    at test (http://web-platform.test:8000/resources/testharness.js:501:18)
    at IdlInterface.test_interface_of (http://web-platform.test:8000/resources/idlharness.js:1551:13)
    at IdlInterface.test_object (http://web-platform.test:8000/resources/idlharness.js:1463:27)

It seems that for a promise object p, p.then is not null, but p.hasOwnProperty("then") returns false.

**Comment by Ms2ger** [comment]
Looks like it should be on the prototype. I'd be happy to review a PR.

**Comment by zhaobin2016** [comment]
It seems that I do not have permission to push a branch or create a pull request. The change is pretty simple, in idlharness.js:466
-        assert_own_property(value, "then", "Attribute with a Promise type has a then property");
+        assert_true("then" in value, "Attribute with a Promise type has a then property");

Could you please grant me permission or could someone fix this at their convenience? Thanks a lot :)

**Comment by jdm** [comment]
There should not be any permissions preventing arbitrary users from creating a pull request. You should be pushing a branch to your own fork, not the w3c repository.

**Comment by bzbarsky** [comment]
https://github.com/w3c/testharness.js/commit/682462ad93b99fc1a719ce05b6d7c63c2c857b7a resolved this, no?

**Comment by jdm** [comment]
Yep.
