### ISSUE TITLE
assert_equals should not throw when formatting cross-origin object

### ISSUE THREAD

**Issue by zcorpan** [w3c/testharness.js#59]
"Note: we eschew assert_equals in a lot of these tests, since the harness ends up throwing when it tries to format a message involving a cross-origin object."
https://critic.hoppipolla.co.uk/ad11a541?review=740

We should fix this.

**Comment by gsnedders** [comment]
So I think this is:


```
<!doctype html>
<script src='/resources/testharness.js'></script>
<script src='/resources/testharnessreport.js'></script>
<iframe src="http://example.com"></iframe>
<script>
  var t = async_test("Simple async test");
  var iframe = document.querySelector("iframe");
  iframe.onload = t.step_func(function(e) { assert_equals("foo", frames[0].location); t.done(); });
</script>
```

This results in:

```
Blocked a frame with origin "http://web-platform.test:8000" from accessing a cross-origin frame.
Error: Blocked a frame with origin "http://web-platform.test:8000" from accessing a cross-origin frame.
    at Error (native)
    at is_node (http://web-platform.test:8000/resources/testharness.js:700:27)
    at format_value (http://web-platform.test:8000/resources/testharness.js:793:17)
    at make_message (http://web-platform.test:8000/resources/testharness.js:2475:36)
    at assert (http://web-platform.test:8000/resources/testharness.js:2420:23)
    at assert_equals (http://web-platform.test:8000/resources/testharness.js:863:13)
    at Object.<anonymous> (http://web-platform.test:8000/foo.html:9:45)
    at Object.Test.step (http://web-platform.test:8000/resources/testharness.js:1380:25)
    at HTMLIFrameElement.<anonymous> (http://web-platform.test:8000/resources/testharness.js:1404:35)
```
